### ISSUE TITLE
DEBUG=build,load,middlewares nodemon app.js 貌似跑不起来

### ISSUE THREAD

**Issue by hjm201** [qddegtya/let-us-koa#1]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! let-us-koa@0.1.0 start: `DEBUG=build,load,middlewares nodemon app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the let-us-koa@0.1.0 start script 'DEBUG=build,load,middlewares nodemon app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the let-us-koa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     DEBUG=build,load,middlewares nodemon app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs let-us-koa
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls let-us-koa
npm ERR! There is likely additional logging output above.

**Comment by qddegtya** [comment]
啊哦，这是因为windows环境下设置env变量的写法不一样。你可以先试试这样：

```bash
set DEBUG=build,load,middlewares && nodemon app.js
```

我会在验证后，调整一下启动方法。

**Comment by iepngs** [comment]
然而启动方法并没有调整，同样问题

**Comment by Cheng007** [comment]
问题依旧
